// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
)

// AdminDao is the manager for logic model data accessing and custom defined data operations functions management.
type AdminDao struct {
	Table   string       // Table is the underlying table name of the DAO.
	Group   string       // Group is the database configuration group name of current DAO.
	Columns AdminColumns // Columns is the short type for Columns, which contains all the column names of Table for convenient usage.
}

// AdminColumns defines and stores column names for table admin.
type AdminColumns struct {
	Id        string // 管理员ID
	UserName  string // 用户名
	RealName  string // 真实姓名
	Password  string // 密码
	Mobile    string // 手机号码
	Email     string // 邮箱
	Status    string // 状态（1-开启，0-关闭）
	Avatar    string // 头像
	GroupId   string // 组织架构
	CreatedAt string // 创建时间
	CreatedId string // 添加人
	UpdatedAt string // 最后更新时间
	UpdatedId string // 最后更新人
	DeletedAt string // 删除时间
	DeletedId string // 删除人
}

//  adminColumns holds the columns for table admin.
var adminColumns = AdminColumns{
	Id:        "id",
	UserName:  "user_name",
	RealName:  "real_name",
	Password:  "password",
	Mobile:    "mobile",
	Email:     "email",
	Status:    "status",
	Avatar:    "avatar",
	GroupId:   "group_id",
	CreatedAt: "created_at",
	CreatedId: "created_id",
	UpdatedAt: "updated_at",
	UpdatedId: "updated_id",
	DeletedAt: "deleted_at",
	DeletedId: "deleted_id",
}

// NewAdminDao creates and returns a new DAO object for table data access.
func NewAdminDao() *AdminDao {
	return &AdminDao{
		Group:   "default",
		Table:   "admin",
		Columns: adminColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *AdminDao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *AdminDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *AdminDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
