// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
)

// RoleDao is the manager for logic model data accessing and custom defined data operations functions management.
type RoleDao struct {
	Table   string      // Table is the underlying table name of the DAO.
	Group   string      // Group is the database configuration group name of current DAO.
	Columns RoleColumns // Columns is the short type for Columns, which contains all the column names of Table for convenient usage.
}

// RoleColumns defines and stores column names for table role.
type RoleColumns struct {
	Id        string // 角色ID
	Name      string // 角色名称
	Dp        string // 数据权限（0-仅自己，1-所在组织架构和下级组织架构，2-所有人）
	CreatedAt string // 创建时间
	CreatedId string // 添加人
	UpdatedAt string // 最后更新时间
	UpdatedId string // 最后更新人
	DeletedAt string // 删除时间
	DeletedId string // 删除人
}

//  roleColumns holds the columns for table role.
var roleColumns = RoleColumns{
	Id:        "id",
	Name:      "name",
	Dp:        "dp",
	CreatedAt: "created_at",
	CreatedId: "created_id",
	UpdatedAt: "updated_at",
	UpdatedId: "updated_id",
	DeletedAt: "deleted_at",
	DeletedId: "deleted_id",
}

// NewRoleDao creates and returns a new DAO object for table data access.
func NewRoleDao() *RoleDao {
	return &RoleDao{
		Group:   "default",
		Table:   "role",
		Columns: roleColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *RoleDao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *RoleDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *RoleDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
